# R8 / ProGuard rules for release builds.

# Rhino is the JavaScript engine the NewPipe extractor uses to run YouTube's
# player script and decipher stream signatures. It targets the JDK, so parts
# of it reference packages that don't exist on Android at all:
#
#   java.beans.*    - JavaBeans introspection
#   javax.script.*  - JSR-223 scripting API
#   jdk.dynalink.*  - invokedynamic linking, used by Rhino's compiling
#                     optimizer
#
# None of these are reachable here: Rhino runs in interpreted mode on Android
# because the platform can't load generated bytecode. Whole packages are
# suppressed rather than individual classes, so a Rhino update pulling in one
# more JDK class doesn't break the release build again.
-dontwarn java.beans.**
-dontwarn javax.script.**
-dontwarn jdk.dynalink.**
-dontwarn org.mozilla.javascript.**

# Rhino resolves classes and members reflectively when it evaluates scripts,
# so its own classes must survive minification or signature deciphering
# breaks at runtime rather than at build time.
-keep class org.mozilla.javascript.** { *; }
-keep class org.mozilla.classfile.** { *; }

# The NewPipe extractor is invoked across the platform channel and parses
# responses reflectively in places; keep it intact.
-keep class org.schabi.newpipe.extractor.** { *; }

# just_audio / audio_service run on ExoPlayer (Media3), which loads renderers
# and extractors by reflection.
-keep class androidx.media3.** { *; }
-dontwarn androidx.media3.**

# Flutter platform channels and app classes
-keep class io.flutter.** { *; }
-keep class com.pulse.music.** { *; }

# AudioService & JustAudio
-keep class com.ryanheise.** { *; }
-dontwarn com.ryanheise.**

# OnAudioQuery plugin
-keep class com.lucasgosioso.on_audio_query.** { *; }
-keep class com.antigravity.on_audio_query_android.** { *; }
-dontwarn com.lucasgosioso.on_audio_query.**
-dontwarn com.antigravity.on_audio_query_android.**

# Hive local storage
-keep class com.ioflux.hive.** { *; }
-dontwarn com.ioflux.hive.**
